// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Swing.Server.Data;

#nullable disable

namespace Swing.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Swing.Server.Models.GameConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("FloatValue")
                        .HasColumnType("REAL");

                    b.Property<int>("IntValue1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntValue2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntValue3")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FloatValue = 0f,
                            IntValue1 = 3,
                            IntValue2 = 800,
                            IntValue3 = 0,
                            Key = "memory"
                        },
                        new
                        {
                            Id = 2,
                            FloatValue = 0f,
                            IntValue1 = 5000,
                            IntValue2 = 12000,
                            IntValue3 = 0,
                            Key = "time"
                        },
                        new
                        {
                            Id = 3,
                            FloatValue = 1.5f,
                            IntValue1 = 15,
                            IntValue2 = 0,
                            IntValue3 = 0,
                            Key = "slider"
                        },
                        new
                        {
                            Id = 4,
                            FloatValue = 100000f,
                            IntValue1 = 5000,
                            IntValue2 = 20000,
                            IntValue3 = 50000,
                            Key = "cost"
                        });
                });

            modelBuilder.Entity("Swing.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Swing.Server.Models.UserGameData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserGameData");
                });

            modelBuilder.Entity("Swing.Server.Models.UserGameData", b =>
                {
                    b.HasOne("Swing.Server.Models.User", "User")
                        .WithMany("UnlockedGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Swing.Server.Models.User", b =>
                {
                    b.Navigation("UnlockedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
